services:
  python:
    image: sitner/python:3.13
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai_agents
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true