services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    image: n8n-custom
    container_name: n8n-custom
    ports:
      - "5678:5678"
    volumes:
      - ./n8n_data:/home/node/.n8n
    environment:
      - NODE_FUNCTION_ALLOW_EXTERNAL=yahoo-finance2,axios
    networks:
      - ai-network
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - ai-network

volumes:
  redis_data:
    driver: local

networks:
  ai-network:
    name: ai-network
    driver: bridge
    external:
      true